// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5rkIzmkZW8hp3Txm7WZHhdUxFxyfXWz8',
    appId: '1:103476684082:web:12753b6c6ce4800a47232b',
    messagingSenderId: '103476684082',
    projectId: 'flutterchat-19fc3',
    authDomain: 'flutterchat-19fc3.firebaseapp.com',
    storageBucket: 'flutterchat-19fc3.firebasestorage.app',
    measurementId: 'G-CMJZH31MTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoWmI2P21saRSZ7QP-U91HICVJC2NJk-w',
    appId: '1:103476684082:android:e99ecd7fc315be1347232b',
    messagingSenderId: '103476684082',
    projectId: 'flutterchat-19fc3',
    storageBucket: 'flutterchat-19fc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzSWEaVbx7o5JlWL5saS1Pa8dpcuZarF8',
    appId: '1:103476684082:ios:c5bdd1dcc2ea85a747232b',
    messagingSenderId: '103476684082',
    projectId: 'flutterchat-19fc3',
    storageBucket: 'flutterchat-19fc3.firebasestorage.app',
    iosBundleId: 'com.raphaeldaka.chatappflutter',
  );
}
